launch-tarpin:
	python3 custom_client.py Tarpin1
	python3 custom_client.py Tarpin2
	python3 custom_client.py Tarpin3
	python3 custom_client.py Tarpin4
	python3 custom_client.py Tarpin5
	python3 custom_client.py Tarpin6