FROM rust:1.85-bookworm AS builder

WORKDIR /usr/src/simeis
COPY . .

RUN cargo install --path .

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/cargo/bin/simeis /usr/local/bin/simeis

EXPOSE 8080

CMD ["simeis"]