FROM rust:1.85-bookworm as builder

WORKDIR /usr/src/simeis
COPY . .

RUN cargo install --path .

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y \
    extra-runtime-dependencies \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/cargo/bin/simeis /usr/local/bin/simeis

CMD ["simeis"]