name: Block pull request
on:
  pull_request:
    types:
      - opened
    branches:
      - 'releases/**'

jobs:
  block-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull
        uses: peter-evans/close-pull@v3
        with:
          comment: Auto-closing pull request
