name: Check build
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  check-doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - name: Install typst-cli
      run: cargo install typst-cli

    - uses: actions/cache@v4
      with:
        path: |
          doc/manual.pdf
        key: ${{ runner.os }}-cargo-${{ hashFiles('doc/manual.typ') }}
      
    - name: Build
      if: steps.cache.outputs.cache-hit != 'true'
      run: make generate-docs
      
  check-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      run: make build-simeis
    - name: Clean artifacts
      run: make clean
