name: Check push
on:
  push:
    branches-ignore: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Cargo Check
      run: make check
    - name: Cargo formatter
      run: make format
    - name: Cargo linter
      run: make lint
    - name: Cargo test
      run: make test
