name: Check build on release branch
on:
  workflow_dispatch:
  push:
    branches: [ "release/**" ]

jobs:
  check-build:
    strategy:
     matrix:
       version: [1.75.0, 1.80.0, 1.85.0, 1.88.0]
       os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build with Rust ${{ matrix.rust }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    
    - name: Build
      run: cargo build --release
