name: Check build on release branch
on:
  workflow_dispatch:
  push:
    branches: [ "release/**" ]

jobs:
  check-build:
    strategy:
     matrix:
       version: ["1.75.0", "1.80.0", "1.85.0", "1.88.0"]
       os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    name: Build avec Rust ${{ matrix.version }} sur ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Rust ${{ matrix.version }}
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.version }}
        override: false
        cache: false
    
    - name: Build
      run: cargo build --release

    - name: Rename binary
      run: mv ./target/release/simeis-server ./target/release/simeis-${{matrix.os}}-${{ github.head_ref.replace("release/", v) }}

    - name: Release
      if: ${{ matrix.version == "1.88.0" }}
      uses: mini-bomba/create-github-release@v1.1.3
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: $RELEASE_VER
          name: $RELEASE_VER
          body: |
            This automatic prerelease is built from commit ${{ env.GIT_HASH }} and was triggered by @${{ github.actor }}
            [Github Actions workflow run that built this prerelease](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Commit message:
            ${{ env.GIT_MESSAGE }}
          files: |
            ./target/release/simeis-${{matrix.os}}-${{ github.head_ref.replace("release/", v) }}
