name: Check build on release branch
on:
  workflow_dispatch:
  push:
    branches: [ "release/**" ]

jobs:
  check-build:
    strategy:
     matrix:
       version: [1.75.0, 1.80.0, 1.85.0, 1.88.0]
       os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Build
      run: make build-simeis
    - name: Clean artifacts
      run: make clean
