name: Deploy

on:
  workflow_dispatch:
    inputs:
      version-tag:
        type: string
        description: 'Existing tag name (eg: v1.9.10)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get deb
        run: wget https://github.com/lepetoc/simeis-ALP/releases/download/${{ inputs.version-tag }}/simeis-ALP.deb -O simeis-ALP.deb

      - name: Check deb presence
        run: ls -la

      - name: Create id_rsa file
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" >> id_rsa
          echo ${{ vars.DEPLOY_SERVER_IP }}
          chmod 600 id_rsa

      - name: Copy deb to server
        run: scp -i id_rsa ./simeis-ALP.deb student@${{ vars.DEPLOY_SERVER_IP }}:~/AlexLucaPierre
          
