name: Deploy

on:
  workflow_dispatch:
    inputs:
      version-tag:
        type: string
        description: 'v1.9.10'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get deb
        run: curl https://github.com/lepetoc/simeis-ALP/releases/download/${{ inputs.version-tag }}/simeis-ALP.deb

      - name: Check deb presence
        run: ls -la
          
