name: Deploy

on:
  workflow_dispatch:
    inputs:
      version-tag:
        type: string
        description: 'Existing tag name (eg: v1.9.10)'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get deb
        run: wget https://github.com/lepetoc/simeis-ALP/releases/download/${{ inputs.version-tag }}/simeis-ALP.deb -O simeis-ALP.deb

      - name: Check deb presence
        run: ls -la

      - name: Create id_rsa file
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Copy deb to server
        run: scp -o StrictHostKeyChecking=no -i ./id_rsa ./simeis-ALP.deb projectrw@${{ vars.DEPLOY_SERVER_IP }}:~/AlexLucaPierre

      - name: Install deb to server
        run:  ssh -i ./id_rsa projectrw@${{ vars.DEPLOY_SERVER_IP }} 'sudo apt install ~/AlexLucaPierre/simeis-ALP.deb -y'

      - name: Ping server
        run: curl ${{ vars.DEPLOY_SERVER_IP }}:${{ vars.DEPLOY_SERVER_PORT }}/ping
          
