name: Analyse Avancée du code 

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'  
      
jobs:
  advanced-analyses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Installation audit
        run: cargo install cargo-audit

      - name: Test Unitaire
        run: cargo test --features heavy-testing

      - name: Debug Mode
        run: cargo build --features heavy-testing

      - name: Test Scripté
        run: |
          chmod +x ./scripts/tests_fonctionnel.sh
          ./scripts/tests_fonctionnel.sh

      - name: Run cargo-audit
        run: cargo audit

      - name: Run Check dependence inutile
        run: |
          chmod +x ./scripts/useless_dependance.sh
          ./scripts/useless_dependance.sh


