name: Analyse Avancée du code

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Installation audit
        run: cargo install cargo-audit
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  tests-unitaires:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test Unitaire
        run: cargo test --features heavy-testing

  build-debug:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Debug Mode
        run: cargo build --features heavy-testing

  tests-fonctionnels:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Test Scripté
        run: |
          chmod +x ./scripts/tests_fonctionnel.sh
          ./scripts/tests_fonctionnel.sh

  audit-securite:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Installation audit
        run: cargo install cargo-audit
      - name: Run cargo-audit
        run: cargo audit

  check-dependances:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Run Check dependence inutile
        run: |
          chmod +x ./scripts/useless_dependance.sh
          ./scripts/useless_dependance.sh