name: Analyse Avancée du code 

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'  
      
jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install cargo-audit
      
        run: cargo install cargo-audit
      - uses: actions/cache@v4
        with:
          path: |
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/src/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run cargo-audit
        run: cargo audit

  heavy-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/cache@v4
        with:
          path: |
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/src/*.rs') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Test Unitaire
        run: cargo test --features heavy-testing

      - name: Debug Mode
        run: cargo build --features heavy-testing

  test-fonctionnel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Scripté
        run: |
          chmod +x ./scripts/tests_fonctionnel.sh
          ./scripts/tests_fonctionnel.sh

  analyse-dependance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Check dependence inutile
        run: |
          chmod +x ./scripts/useless_dependance.sh
          ./scripts/useless_dependance.sh